scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'sentence'
    scrape_interval: 10s
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['sentence:8105']
  - job_name: 'verb'
    scrape_interval: 10s
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['verb:8100']
  - job_name: 'subject'
    scrape_interval: 10s
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['subject:8101']
  - job_name: 'article'
    scrape_interval: 10s
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['article:8102']
  - job_name: 'adjective'
    scrape_interval: 10s
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['adjective:8103']
  - job_name: 'noun'
    scrape_interval: 10s
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['noun:8104']





